services:
  backend:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_erpnext
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - apps:/home/frappe/frappe-bench/apps
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: ${MARIADB_DB_NAME}
      DB_PORT: ${MARIADB_PORT_VAR}
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_configurator
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: ${MARIADB_DB_NAME}
      DB_PORT: ${MARIADB_PORT_VAR}
      REDIS_CACHE: redis-cache:${REDIS_PORT_VAR}
      REDIS_QUEUE: redis-queue:${REDIS_PORT_VAR}
      SOCKETIO_PORT: ${SOCKETIO_PORT_VAR}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_create_site
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t ${TIMEOUT_BEFORE_EXIT} ${MARIADB_DB_NAME}:${MARIADB_PORT_VAR};
        wait-for-it -t ${TIMEOUT_BEFORE_EXIT} redis-cache:${REDIS_PORT_VAR};
        wait-for-it -t ${TIMEOUT_BEFORE_EXIT} redis-queue:${REDIS_PORT_VAR};
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep ${SLEEP_INTERVAL};
          if (( `date +%s`-start > ${TIMEOUT_BEFORE_EXIT} )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;

  db:
    image: mariadb:${MARIADB_IMAGE_VERSION}
    container_name: frappe_mariadb
    networks:
      - frappe_network
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_frontend
    networks:
      - frappe_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:${BACKEND_PORT_VAR}
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:${SOCKETIO_PORT_VAR}
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: ${TIMEOUT_BEFORE_EXIT}
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      # - ./erptia/public:/home/frappe/frappe-bench/apps/erptia/public
      - apps:/home/frappe/frappe-bench/apps
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "${FRONTEND_PORT_VAR}:8080"

  queue-long:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_queue_long
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_queue_short
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:${REDIS_IMAGE_VERSION}
    container_name: frappe_redis_queue
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:${REDIS_IMAGE_VERSION}
    container_name: frappe_redis_cache
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_scheduler
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_websocket
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  apps:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
